# Generated by Django 2.2.7 on 2020-11-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wear', '0002_auto_20201113_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclothes',
            name='brand',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userclothes',
            name='item',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userclothes',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='userclothes',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
